### ISSUE TITLE
Kaprekar Number or not using Java language

### ISSUE THREAD

**Issue by ssbeast** [DSC-ChitkaraUniv/HacktoberFest-2020#122]
A number is kaprekar if the representation of its square can be split into two parts that add up to the original number. For instance, 45 is a Kaprekar number, because 45^2 = 2025 and 20 + 25 = 45. Whereas 13 is not as 13^2 = 169 which can be split in two ways (1+69) and (16+9), but any of them is not 13. The number 1 is Kaprekar, because 1^2 = 01, and  0 + 1 = 1.

Complete the following program using JAVA langauage.

**Comment by Yashank18** [comment]
Please provide description about your issue

**Comment by ssbeast** [comment]
@Yashank18 I have added description about issue!!
Please assign me this issue.
